# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iQPyIolMu4FLAvn7tHgyG24JX3JzQXCY
"""

import streamlit as st
import requests
import pandas as pd
import google.generativeai as genai

# [보안] st.secrets를 사용하여 키를 관리하세요 (배포 시 필수)
# 로컬 테스트를 위해 잠시 유지하되, 배포 전에는 반드시 제거하세요.
# StreamlitSecretNotFoundError 방지를 위해 API 키를 직접 할당합니다.
SCHOOL_API_KEY = "0a613ca799bc4975be034eb26bc2e9c9"
GEMINI_API_KEY = "AIzaSyBsWW_QCAiQ21oGPVTFyo6d9X5hEdEYT-Y"

# Gemini 설정
genai.configure(api_key=GEMINI_API_KEY)
model = genai.GenerativeModel('gemini-2.5-flash')

# 세션 상태 초기화 (데이터 유지용)
if 'school_data' not in st.session_state:
    st.session_state.school_data = None

def get_school_info(school_name):
    # 실제 학교알리미 초중등교육기관 기본정보 API 주소 예시
    url = "https://www.schoolinfo.go.kr/openApi/api/school/baseInfo.do"
    params = {
        'apiKey': SCHOOL_API_KEY,
        's_schul_nm': school_name,
        'format': 'json'
    }

    try:
        # 실제 API 호출 시 주석 해제
        response = requests.get(url, params=params)
        res_data = response.json()

        # 데모용 데이터 (실제 호출 성공 시 res_data에서 추출하도록 수정 필요)
        return {
            "name": school_name,
            "total_students": 450,
            "teacher_ratio": 12.8,
            "it_status": "매우 우수",
            "after_school": 24
        }
    except Exception as e:
        st.error(f"API 호출 중 오류 발생: {e}")
        return None

def analyze_school(data):
    prompt = f"학교 컨설턴트로서 다음 데이터를 SWOT 분석하고 전략을 제안해줘: {data}"
    response = model.generate_content(prompt)
    return response.text

# --- UI 레이아웃 ---
st.set_page_config(page_title="스쿨 인사이트 AI", layout="wide")
st.title("🏫 스쿨 인사이트 AI")

with st.sidebar:
    st.header("🔍 검색")
    target = st.text_input("학교명 입력")
    if st.button("데이터 수집"):
        with st.spinner("정보를 가져오는 중..."):
            result = get_school_info(target)
            if result:
                st.session_state.school_data = result
                st.success("데이터 로드 완료!")

# 메인 화면
if st.session_state.school_data:
    data = st.session_state.school_data
    st.subheader(f"📊 {data['name']} 핵심 지표")

    c1, c2, c3 = st.columns(3)
    c1.metric("학생 수", f"{data['total_students']}명")
    c2.metric("교사당 학생", f"{data['teacher_ratio']}명")
    c3.metric("방과후 강좌", f"{data['after_school']}개")

    st.divider()

    if st.button("🚀 AI 심층 분석 실행"):
        with st.spinner("전문가 AI가 분석 중..."):
            report = analyze_school(data)
            st.markdown("### 📝 분석 리포트")
            st.write(report)

            st.download_button("리포트 저장", report, file_name="report.txt")
else:
    st.info("사이드바에서 학교를 검색해 주세요.")

